// Generated by CoffeeScript 1.7.1

/*
Add more links to vocabuary.com word page.
Created by tux, Sat Feb  8 23:48:59 CST 2014
 */

(function() {
  var DEBUG, DOMModificationHandler, container, mangle, sites;

  DEBUG = true;

  DEBUG = false;

  container = "div.wordPage";

  sites = [
    {
      'name': 'Dictionary.com',
      'link': 'http://dictionary.reference.com/browse/'
    }, {
      'name': 'Youdao',
      'link': 'http://dict.youdao.com/search?q='
    }, {
      'name': 'Etymology',
      'link': 'http://etymonline.com/index.php?search='
    }, {
      'name': 'Google Images',
      'link': 'http://images.google.com/images?q='
    }
  ];

  mangle = function() {
    var link, links, site, word, _i, _len, _results;
    $("" + container + " a.ext-link").remove();
    word = $.trim($("" + container + " h1").text());
    links = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = sites.length; _i < _len; _i++) {
        site = sites[_i];
        _results.push("<a target='_blank' class='ext-link tbutton' href='" + site["link"] + word + "'>" + site["name"] + "</a>");
      }
      return _results;
    })();
    if (DEBUG) {
      console.log("word: " + word);
      console.log(links);
    }
    _results = [];
    for (_i = 0, _len = links.length; _i < _len; _i++) {
      link = links[_i];
      _results.push($(link).appendTo("" + container + " div.tools"));
    }
    return _results;
  };

  DOMModificationHandler = function() {
    $(this).unbind("DOMSubtreeModified");
    return setTimeout((function() {
      mangle();
      return $(container).bind("DOMSubtreeModified", DOMModificationHandler);
    }), 4000);
  };

  $(container).bind("DOMSubtreeModified", DOMModificationHandler);

  $(document).click(mangle);

}).call(this);

//# sourceMappingURL=functions.map
